"""
Heartbeat Formatting and Posting Helpers

Pure formatting functions and thin API wrappers extracted from heartbeat.py.
These handle comment text generation and error/cancellation posting to Paperclip.
"""

import logging
from typing import List

from .paperclip_client import PaperclipClient, PaperclipAPIError

logger = logging.getLogger(__name__)


def _format_success_comment(output: str, score: int) -> str:
    """Format a success comment for Paperclip."""
    # Truncate output for comment (Paperclip comments should be concise)
    truncated = output[:3000] if output else "No output"
    return f"## Completed (score: {score}/100)\n\n{truncated}"


def _format_blocked_comment(output: str, score: int, threshold: int) -> str:
    """Format a blocked comment when quality gate fails."""
    truncated = output[:2000] if output else "No output"
    return (
        f"## Blocked — quality below threshold\n\n"
        f"Score: {score}/100 (threshold: {threshold})\n\n"
        f"### Output so far\n\n{truncated}\n\n"
        f"**Needs review or manual refinement.**"
    )


def _format_clarification_comment(questions: List[str]) -> str:
    """Format a clarification request comment for Paperclip."""
    lines = ["## Clarification Needed\n"]
    lines.append("I need some clarification before I can continue:\n")
    for i, q in enumerate(questions, 1):
        lines.append(f"{i}. {q}")
    lines.append("\n_Please reply to this comment with your answers._")
    return "\n".join(lines)


def _format_upgrade_comment(description: str, branch: str, commit: str) -> str:
    """Format a self-upgrade notification comment for the source issue."""
    commit_short = commit[:8] if commit else "unknown"
    return (
        f"## Self-Upgrade Proposed\n\n"
        f"While working on this task the agent identified an opportunity to "
        f"improve its own code and has committed a validated change.\n\n"
        f"**Improvement:** {description}\n"
        f"**Branch:** `{branch}`\n"
        f"**Commit:** `{commit_short}`\n\n"
        f"_A dedicated self-upgrade issue has been created for review._"
    )


def _format_upgrade_issue_body(
    description: str, branch: str, commit: str, source_issue_id: str,
) -> str:
    """Format the body for a dedicated self-upgrade Paperclip issue."""
    commit_short = commit[:8] if commit else "unknown"
    return (
        f"The agent identified a recurring quality issue and has proposed "
        f"a validated code change to address it.\n\n"
        f"## Details\n\n"
        f"**Improvement:** {description}\n"
        f"**Branch:** `{branch}`\n"
        f"**Commit:** `{commit_short}`\n"
        f"**Triggered by:** Issue `{source_issue_id}`\n\n"
        f"## Validation Gates Passed\n\n"
        f"- Path validation (only agents/ directory, immutable files blocked)\n"
        f"- Diff size check (under 500 lines)\n"
        f"- Full pytest suite\n"
        f"- Bandit security scan\n\n"
        f"## How to Review\n\n"
        f"1. Check out branch `{branch}`\n"
        f"2. Review the diff for correctness\n"
        f"3. Merge to main if approved\n\n"
        f"_This issue was auto-generated by the Vibe self-upgrade pipeline._"
    )


def _post_failure(client: PaperclipClient, issue_id: str, error: str) -> None:
    """Post a failure comment and set issue to blocked."""
    try:
        client.update_issue(
            issue_id,
            status="blocked",
            comment=f"## Workflow Error\n\n```\n{error[:1000]}\n```\n\n**Agent encountered an error. Needs investigation.**",
        )
    except PaperclipAPIError as e:
        logger.error("Failed to post failure comment: %s", e)


def _post_cancelled(client: PaperclipClient, issue_id: str) -> None:
    """Post a cancellation comment. Issue is already 'cancelled' in Paperclip."""
    try:
        client.add_comment(
            issue_id,
            "## Cancelled\n\nWorkflow was cancelled before completion.",
        )
    except PaperclipAPIError as e:
        logger.warning("Failed to post cancellation comment (non-fatal): %s", e)
