"""
Output Node Implementations

Formatting and posting methods extracted from the AgentNodes monolith.
These are mixed into AgentNodes via OutputNodesMixin.
"""

import logging

from .state import AgentState

logger = logging.getLogger(__name__)


class OutputNodesMixin:
    """
    Mixin containing output formatting and posting node methods.

    Depends on self.config (SystemConfig).
    """

    def format_for_mattermost(self, state: AgentState) -> AgentState:
        """
        Format the final output for posting to Mattermost.

        Creates a nicely formatted message with:
        - Success indicator
        - Stats (iterations, score)
        - The actual output
        - Metadata
        """
        final_output = state.get("specialist_output", "")
        final_score = state.get("output_critic_score", 0)
        iterations = state.get("iteration_count", 0)

        message = f"""✅ **Task Completed** (Score: {final_score}/100)
🔄 **Iterations**: {iterations}/{state.get('max_iterations', 3)}
📝 **Request**: {state['user_request'][:100]}{"..." if len(state['user_request']) > 100 else ""}

**Result**:
{final_output}

---
_Generated by Multi-Agent AI System_
Session: {state.get('session_id', 'N/A')}
Time: {state.get('total_time_seconds', 0):.1f}s
"""

        state["final_output"] = final_output
        state["mattermost_message"] = message

        logger.info("Formatted output for Mattermost")

        return state

    def post_to_mattermost(self, state: AgentState) -> AgentState:
        """
        Post the formatted message to Mattermost.

        When running standalone (CLI), supports:
        - Webhook posting: fire-and-forget via incoming webhook URL
        - Bot API posting: full API via bot token (supports threads)
        """
        message = state.get("mattermost_message", "")
        if not message:
            logger.warning("No mattermost_message in state, skipping post")
            return state

        mm_cfg = getattr(self.config, "mattermost", None) if self.config else None
        if mm_cfg is None or not mm_cfg.enabled:
            logger.info("Mattermost posting disabled, skipping")
            return state

        posted = False

        # --- Bot API path (preferred — supports threads) ---
        if mm_cfg.bot_token and mm_cfg.mattermost_url:
            try:
                from .messenger_client import MattermostClient

                client = MattermostClient(
                    url=mm_cfg.mattermost_url,
                    bot_token=mm_cfg.bot_token,
                )
                channel_id = state.get("channel_id", mm_cfg.default_channel)
                thread_id = state.get("thread_id")

                post_id = client.send_channel_message(
                    channel_id=channel_id,  # type: ignore[arg-type]
                    message=message,
                    root_id=thread_id,
                )
                if post_id:
                    state["mattermost_message_id"] = post_id
                    logger.info(f"Posted to Mattermost via bot API (post_id={post_id})")
                    posted = True
                else:
                    logger.error("Bot API post returned no post_id")
                return state
            except Exception as e:
                logger.error(f"Bot API posting failed: {e}")
                # Only fall through to webhook if we are sure nothing was sent
                if posted:
                    return state

        # --- Webhook path (fallback) ---
        if mm_cfg.webhook_url:
            try:
                import requests as _requests

                payload = {
                    "text": message,
                    "channel": mm_cfg.default_channel,
                    "username": mm_cfg.username,
                }
                resp = _requests.post(mm_cfg.webhook_url, json=payload, timeout=10)
                resp.raise_for_status()
                logger.info("Posted to Mattermost via webhook")
            except Exception as e:
                logger.error(f"Webhook posting failed: {e}")
        else:
            logger.warning("No Mattermost credentials configured (bot_token or webhook_url)")

        return state
