"""
Skill Generator Node - Creates ephemeral skills with reinforcement learning.

This node is called when the router detects a need for a skill that doesn't
exist in official or local tiers. It generates a new ephemeral skill and
registers it in the temp tier.

Reinforcement pipeline (closed loop):
  1. Generate skill (LLM-driven or template, RAG from outcome store)
  2. Skill is used by specialist, scored by critic
  3. Outcome recorded in SkillOutcomeStore
  4. Next generation retrieves top-K examples from store
  5. Low-scoring skills trigger self-refinement

When a base_model (LLM backend) is available, the workflow and best practices
sections are generated by the LLM, informed by RAG examples.  When no LLM is
available (or the call fails), the generator falls back to static templates.
"""

import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
import logging
from .state import AgentState
from .skill_registry import SkillRegistry
from .skill_outcome_store import SkillOutcomeStore

logger = logging.getLogger(__name__)

# Score below which a skill is eligible for self-refinement
REFINEMENT_THRESHOLD = 70

# System prompt for LLM-driven skill generation
_SKILL_DESIGNER_SYSTEM_PROMPT = """\
You are a skill designer. You create workflow instructions that guide \
AI specialists in performing specific tasks.

You will be given a task type, a specification, and optionally examples \
of past workflows that scored well or poorly. Your job is to produce:

1. A "How It Works" section: numbered workflow steps tailored to the \
specific task. Each step should have a bold title and a clear description. \
Be concrete — reference the specification where relevant.

2. A "Best Practices" section: numbered guidelines specific to this task \
type. Avoid generic advice ("be careful") — each point should be actionable.

Output ONLY the two sections in markdown, starting with "## How It Works" \
and "## Best Practices". Do not include frontmatter, titles, or any other \
sections."""


class SkillGeneratorNode:
    """
    Generates ephemeral skills on-demand using LLM-driven or template-based
    generation with retrieval-augmented learning from the outcome store.

    When the router identifies a capability gap (no matching skill in
    official or local tiers), this node creates a new skill and saves
    it to the temp/ directory for immediate use.
    """

    # Path to the canonical skill template (synced from anthropics/skills)
    _TEMPLATE_PATH = Path(__file__).resolve().parent.parent / "vibe_skills" / "template" / "SKILL.md"

    def __init__(
        self,
        skill_registry: SkillRegistry,
        outcome_store: Optional[SkillOutcomeStore] = None,
        base_model: Any = None,
        adapter_registry: Any = None,
    ):
        """
        Initialize skill generator.

        Args:
            skill_registry: Shared SkillRegistry instance
            outcome_store:  Shared SkillOutcomeStore for RAG.
                           If None, falls back to pure-template generation.
            base_model:     LLM backend for generating tailored workflows.
                           If None, falls back to static templates.
            adapter_registry: Optional AdapterRegistry for simulation-based
                           skill vetting.  When provided and VIBE_SIM_VET_SKILLS
                           is enabled, newly generated skills are vetted
                           offline before use.
        """
        self.name = "skill_generator"
        self.skill_registry = skill_registry
        self.outcome_store = outcome_store
        self.base_model = base_model
        self.adapter_registry = adapter_registry
        self._skill_template = self._load_skill_template()

    @classmethod
    def _load_skill_template(cls) -> Optional[str]:
        """Load the canonical SKILL.md template if available."""
        if cls._TEMPLATE_PATH.is_file():
            try:
                content = cls._TEMPLATE_PATH.read_text(encoding="utf-8")
                logger.debug(f"Loaded skill template from {cls._TEMPLATE_PATH}")
                return content
            except OSError as e:
                logger.warning(f"Failed to load skill template: {e}")
        return None

    def execute(self, state: AgentState) -> AgentState:
        """
        Generate ephemeral skills for any discovered skills marked as "ephemeral".

        Args:
            state: Current agent state with discovered_skills

        Returns:
            Updated state with generated skills registered
        """
        discovered_skills = state.get("discovered_skills", [])

        # Find all ephemeral skills that need generation
        ephemeral_skills = [
            s for s in discovered_skills
            if s["tier"] == "ephemeral"
        ]

        if not ephemeral_skills:
            logger.info("No ephemeral skills to generate")
            return state

        logger.info(f"🔧 Generating {len(ephemeral_skills)} ephemeral skills")

        # Generate each ephemeral skill
        for skill_info in ephemeral_skills:
            task_type = skill_info["task_type"]
            specification = state.get("specification", "")

            # Generate skill using skill-creator pattern
            skill_name, skill_path = self._generate_skill(
                task_type=task_type,
                specification=specification
            )

            # Update the skill info with generated details
            skill_info["skill_name"] = skill_name
            skill_info["skill_path"] = str(skill_path)
            skill_info["tier"] = "temp"  # Reflect actual registry tier

            # Add to skills_in_use
            skills_in_use = state.get("skills_in_use", [])
            skills_in_use.append(skill_name)
            state["skills_in_use"] = skills_in_use

        # Update state with modified discovered_skills
        state["discovered_skills"] = discovered_skills

        # Log generation
        debug_info = state.get("debug_info", {})
        debug_info["generated_skills"] = {
            "count": len(ephemeral_skills),
            "skills": [s["skill_name"] for s in ephemeral_skills]
        }
        state["debug_info"] = debug_info

        return state

    def _generate_skill(
        self,
        task_type: str,
        specification: str
    ) -> Tuple[str, Path]:
        """
        Generate a new skill using skill-creator pattern.

        If a temp skill with the same name already exists (retained from a
        prior session), the SKILL.md content is refreshed but accumulated
        usage metrics (usage_count, scores, avg_score) are preserved so that
        the promotion path is not reset.

        Args:
            task_type: Type of task (e.g., "test_generation", "security_audit")
            specification: User specification that triggered skill need

        Returns:
            Tuple of (skill_name, skill_path)
        """
        # Create skill name from task type
        skill_name = f"ephemeral-{task_type.replace('_', '-')}"
        skill_path = self.skill_registry.temp_dir / skill_name
        skill_path.mkdir(parents=True, exist_ok=True)

        # Generate SKILL.md content (LLM-driven or template fallback)
        skill_content = self._create_skill_content(task_type, specification)

        # Write SKILL.md file
        skill_file = skill_path / "SKILL.md"
        with open(skill_file, 'w', encoding='utf-8') as f:
            f.write(skill_content)

        # Check if a retained temp skill with this name already exists —
        # if so, preserve its accumulated usage data instead of overwriting.
        existing = self.skill_registry.index["tiers"]["temp"]["skills"].get(skill_name)

        if existing:
            # Refresh the integrity hash for the new content but keep metrics
            self.skill_registry.security.store_integrity_hash(skill_name, skill_content)
            self.skill_registry._save_index()
            logger.info(
                f"♻️ Refreshed existing temp skill: {skill_name} "
                f"(preserving {existing.get('usage_count', 0)} uses, "
                f"avg score {existing.get('avg_score', 0):.0f})"
            )
        else:
            # Brand new skill — register from scratch
            task_types = [task_type]
            description = self._create_description(task_type)

            self.skill_registry.register_skill(
                name=skill_name,
                description=description,
                tier="temp",
                task_types=task_types,
                skill_path=skill_path
            )
            logger.info(f"✅ Generated new ephemeral skill: {skill_name}")

        # ── Offline skill vetting via simulation ──
        self._vet_and_maybe_refine(
            skill_name=skill_name,
            skill_content=skill_content,
            task_type=task_type,
            specification=specification,
            skill_path=skill_path,
        )

        return skill_name, skill_path

    def _vet_and_maybe_refine(
        self,
        skill_name: str,
        skill_content: str,
        task_type: str,
        specification: str,
        skill_path: "Path",
    ) -> None:
        """Skill vetting placeholder.

        Inline simulation vetting has been removed. Vetting is now handled
        externally via the MiroFish service when needed.
        """
        return

    # ------------------------------------------------------------------
    # Skill content generation (LLM-driven with template fallback)
    # ------------------------------------------------------------------

    def _create_skill_content(self, task_type: str, specification: str) -> str:
        """
        Create SKILL.md content based on task type and specification.

        Generation strategy (in priority order):
          1. LLM-driven: base_model generates tailored workflow + best practices,
             informed by RAG examples from the outcome store.
          2. Template + RAG: static workflow template with learned patterns
             injected as additional sections (cold start or no LLM).
          3. Pure template: static workflow only (no outcome store, no LLM).

        Frontmatter, "When to Use", "Context", and "Notes" are always
        templated — these are deterministic and shouldn't be hallucinated.

        Args:
            task_type: Type of task
            specification: User specification

        Returns:
            SKILL.md content as string
        """
        task_type_readable = task_type.replace('_', ' ').title()
        skill_name = f"ephemeral-{task_type.replace('_', '-')}"
        description = self._create_description(task_type)

        # Build frontmatter matching the canonical template schema
        # (name + description as top-level fields, matching official skills)
        allowed_tools = self._allowed_tools_for_task(task_type)
        quality_criteria = self._quality_criteria_for_task(task_type)
        quality_line = ""
        if quality_criteria:
            quality_line = f"quality-criteria: {' | '.join(quality_criteria)}\n"

        frontmatter = f"""---
name: {skill_name}
description: {description}
license: Apache-2.0
metadata:
  author: vibe
  version: "1.0"
  generated: true
allowed-tools: {allowed_tools}
{quality_line}---

# {task_type_readable}

Ephemeral skill generated on-demand for {task_type} tasks.

## When to Use

Use this skill when the task involves {task_type.replace('_', ' ')} and requires:
- Specific domain knowledge for {task_type}
- Systematic approach to {task_type.replace('_', ' ')}
- Quality validation and best practices

"""

        # Try LLM-driven generation for the middle sections
        llm_sections = self._generate_sections_with_llm(task_type, specification)

        if llm_sections is not None:
            workflow_and_practices = llm_sections
        else:
            # Fallback: static template + RAG as appended section
            workflow = "## How It Works\n" + self._create_workflow_template(
                task_type, specification
            )
            learned = self._build_learned_patterns_section(task_type)
            practices = self._create_best_practices_template(task_type)
            workflow_and_practices = workflow + "\n" + learned + practices

        # Deterministic context and notes (never LLM-generated)
        context_and_notes = f"""
## Context

This skill was generated for the following specification:
```
{specification[:500]}{"..." if len(specification) > 500 else ""}
```

## Notes

This is an ephemeral skill generated automatically. If this skill proves
valuable (used 3+ times with avg quality >= 85), it will be promoted to
the local tier for permanent storage.
"""

        return frontmatter + workflow_and_practices + context_and_notes

    # ------------------------------------------------------------------
    # LLM-driven generation
    # ------------------------------------------------------------------

    def _generate_sections_with_llm(
        self, task_type: str, specification: str
    ) -> Optional[str]:
        """
        Use the LLM to generate tailored workflow and best practices.

        Builds a prompt with the task context and RAG examples, calls the
        LLM, validates the output contains the required sections, and
        returns the generated markdown.

        Returns None if:
          - No base_model available
          - LLM call fails
          - Output fails validation (missing required sections)

        In all failure cases, the caller falls back to static templates.
        """
        if self.base_model is None:
            return None

        prompt = self._build_llm_prompt(task_type, specification)

        try:
            messages = [
                {"role": "system", "content": _SKILL_DESIGNER_SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ]
            response = self.base_model.generate(
                messages,
                temperature=0.4,
                max_tokens=1200,
            )
        except Exception as e:
            logger.warning(f"LLM skill generation failed, using template: {e}")
            return None

        # Validate: must contain both required section headings
        if not self._validate_llm_output(response):
            logger.warning(
                "LLM output missing required sections, using template"
            )
            return None

        logger.info(
            f"🤖 LLM-generated workflow for {task_type} "
            f"({len(response)} chars)"
        )
        return response  # type: ignore[no-any-return]

    def _build_llm_prompt(self, task_type: str, specification: str) -> str:
        """
        Build the user prompt for LLM-driven skill generation.

        Includes:
          - Task type and specification context
          - Positive examples from the outcome store (if available)
          - Negative examples with critic feedback (if available)
        """
        task_readable = task_type.replace("_", " ")

        parts = [
            f"Task type: {task_readable}",
            f"Specification:\n{specification[:600]}",
        ]

        # Add RAG examples if available
        if self.outcome_store is not None:
            positive = self.outcome_store.retrieve_positive_examples(
                task_type, top_k=2
            )
            negative = self.outcome_store.retrieve_negative_examples(
                task_type, top_k=1
            )

            if positive:
                parts.append("\n--- HIGH-SCORING EXAMPLES (learn from these) ---")
                for i, ex in enumerate(positive, 1):
                    workflow = self._extract_workflow_excerpt(
                        ex.get("skill_content", "")
                    )
                    feedback = ex.get("feedback", "")
                    score = ex.get("score", 0)
                    parts.append(f"\nExample {i} (score: {score}/100):")
                    if workflow:
                        parts.append(workflow)
                    if feedback:
                        parts.append(f"Critic: {feedback[:200]}")

            if negative:
                parts.append("\n--- LOW-SCORING EXAMPLES (avoid these patterns) ---")
                for ex in negative:
                    feedback = ex.get("feedback", "")
                    score = ex.get("score", 0)
                    parts.append(
                        f"Score {score}/100 — Critic: {feedback[:200]}"
                    )

        parts.append(
            f"\nGenerate a tailored workflow and best practices for this "
            f"{task_readable} task."
        )

        return "\n\n".join(parts)

    @staticmethod
    def _validate_llm_output(response: str) -> bool:
        """
        Validate that the LLM output contains the required sections.

        Required:
          - "## How It Works" heading
          - "## Best Practices" heading
          - At least one numbered step (e.g., "1. " or "1. **")
        """
        if not response or len(response) < 50:
            return False
        if "## How It Works" not in response:
            return False
        if "## Best Practices" not in response:
            return False
        # Must contain at least one numbered step at the start of a line
        # (plain "1." matches version numbers like "1.0" — false positive)
        if not re.search(r'^\d+\.\s', response, re.MULTILINE):
            return False
        return True

    # ------------------------------------------------------------------
    # Template fallback (static workflows + RAG as appended section)
    # ------------------------------------------------------------------

    def _build_learned_patterns_section(self, task_type: str) -> str:
        """
        Build the "Learned Patterns" section from the outcome store.

        Used in the template fallback path: RAG examples are appended as
        a separate section rather than feeding into LLM generation.

        Returns empty string on cold start or when no outcome store.
        """
        if self.outcome_store is None:
            return ""

        positive = self.outcome_store.retrieve_positive_examples(task_type, top_k=3)
        negative = self.outcome_store.retrieve_negative_examples(task_type, top_k=1)

        if not positive and not negative:
            return ""

        parts = ["\n## Learned Patterns (from past outcomes)\n"]

        if positive:
            parts.append(
                "The following patterns produced HIGH-SCORING outputs "
                "for this task type. Incorporate these approaches:\n"
            )
            for i, ex in enumerate(positive, 1):
                score = ex.get("score", 0)
                feedback = ex.get("feedback", "")
                workflow_excerpt = self._extract_workflow_excerpt(
                    ex.get("skill_content", "")
                )
                parts.append(
                    f"### Positive Example {i} (score: {score}/100)\n"
                )
                if workflow_excerpt:
                    parts.append(f"```\n{workflow_excerpt}\n```\n")
                if feedback:
                    parts.append(f"*Critic feedback*: {feedback[:200]}\n")
                parts.append("")

        if negative:
            parts.append(
                "### Anti-Patterns (avoid these)\n\n"
                "The following approaches produced LOW-SCORING outputs. "
                "Do NOT repeat these mistakes:\n"
            )
            for ex in negative:
                score = ex.get("score", 0)
                feedback = ex.get("feedback", "")
                parts.append(f"- **Score {score}/100**: {feedback[:200]}\n")

        return "\n".join(parts) + "\n"

    @staticmethod
    def _extract_workflow_excerpt(skill_content: str) -> str:
        """
        Extract the workflow/how-it-works section from a SKILL.md.

        Returns the content between "## How It Works" and the next ## heading,
        truncated to 500 chars.
        """
        if not skill_content:
            return ""

        marker = "## How It Works"
        start = skill_content.find(marker)
        if start == -1:
            return ""

        # Skip past the marker line
        start = skill_content.find("\n", start)
        if start == -1:
            return ""
        start += 1

        # Find next section heading
        next_heading = skill_content.find("\n## ", start)
        if next_heading == -1:
            excerpt = skill_content[start:]
        else:
            excerpt = skill_content[start:next_heading]

        excerpt = excerpt.strip()
        if len(excerpt) > 500:
            excerpt = excerpt[:500] + "..."
        return excerpt

    # ------------------------------------------------------------------
    # Layer 3: Self-Refinement
    # ------------------------------------------------------------------

    def refine_skill(
        self,
        skill_name: str,
        task_type: str,
        original_content: str,
        score: int,
        feedback: str,
        specification: str,
    ) -> Optional[str]:
        """
        Refine a low-scoring skill using critic feedback.

        Called by skill_cleanup when a skill scores below REFINEMENT_THRESHOLD.
        Regenerates the SKILL.md incorporating the critic's specific feedback
        about what went wrong.

        Args:
            skill_name:       Name of the skill to refine
            task_type:        Task type classification
            original_content: The SKILL.md content that scored poorly
            score:            The critic score (0-100)
            feedback:         The critic's feedback text
            specification:    The original specification

        Returns:
            The refined SKILL.md content, or None if refinement not possible.
        """
        if score >= REFINEMENT_THRESHOLD:
            return None

        logger.info(
            f"🔄 Refining skill {skill_name} "
            f"(score={score}, below threshold={REFINEMENT_THRESHOLD})"
        )

        # Build a refinement-aware skill content
        refined = self.draft_refined_content(
            task_type=task_type,
            specification=specification,
            original_content=original_content,
            feedback=feedback,
            score=score,
        )

        # Write the refined SKILL.md
        skill_path = self._find_skill_path(skill_name)
        if skill_path is None:
            logger.warning(f"Cannot refine {skill_name}: not found in registry")
            return None

        skill_file = skill_path / "SKILL.md"
        with open(skill_file, "w", encoding="utf-8") as f:
            f.write(refined)

        # Update integrity hash
        self.skill_registry.security.store_integrity_hash(skill_name, refined)
        self.skill_registry._save_index()

        logger.info(f"✅ Refined skill {skill_name} with critic feedback")
        return refined

    def draft_refined_content(
        self,
        task_type: str,
        specification: str,
        original_content: str,
        feedback: str,
        score: int,
    ) -> str:
        """Compute refined SKILL.md content incorporating critic feedback.

        Pure function — no file I/O, no registry writes. Callers are
        responsible for persisting the result (see
        ``agents.self_upgrade.tier1a_builder.Tier1aBuilder``) or discarding
        it if the refinement is not worth keeping.

        Inserts a "Refinement Directives" section before "## Context" in the
        newly-generated base skill content, encoding the critic's complaints
        as hard requirements the refined skill must address.
        """
        # Start from a fresh generation (with RAG patterns)
        base = self._create_skill_content(task_type, specification)

        # Insert refinement directives before "## Context"
        refinement_section = f"""
## Refinement Directives (IMPORTANT)

This skill was refined after scoring {score}/100. The critic identified
these specific issues that MUST be addressed:

{feedback[:800]}

**Requirements from refinement:**
- Address ALL issues listed above before considering the task complete
- Pay special attention to the areas the critic flagged as deficient
- Validate output against each critique point before finalizing

"""
        # Insert before "## Context"
        anchor = "## Context"
        anchor_pos = base.find(anchor)
        if anchor_pos != -1:
            base = base[:anchor_pos] + refinement_section + base[anchor_pos:]
        else:
            base += refinement_section

        return base

    def _find_skill_path(self, skill_name: str) -> Optional[Path]:
        """Look up the filesystem path for a skill from the registry."""
        for tier in ["temp", "local", "official"]:
            skill_data = self.skill_registry.index["tiers"][tier]["skills"].get(
                skill_name
            )
            if skill_data:
                return Path(skill_data["path"])
        return None

    # ------------------------------------------------------------------
    # Template helpers
    # ------------------------------------------------------------------

    def _create_description(self, task_type: str) -> str:
        """Create skill description based on task type."""
        descriptions = {
            "test_generation": "Generates comprehensive unit tests with high coverage and edge case handling",
            "security_audit": "Performs security audits identifying vulnerabilities and providing remediation",
            "documentation": "Creates clear, comprehensive documentation with examples and best practices",
            "performance_optimization": "Analyzes and optimizes code for performance, identifying bottlenecks",
            "debugging": "Systematically debugs issues, identifies root causes, and provides fixes",
            "refactoring": "Refactors code for better structure, maintainability, and adherence to best practices",
            "code_generation": "Generates high-quality code following best practices and design patterns",
            "research": "Researches topics thoroughly with authoritative sources and actionable summaries",
            "writing": "Produces clear, well-structured written content tailored to the audience",
            "data_analysis": "Analyzes data with appropriate methods, clear visualizations, and actionable insights",
            "planning": "Creates structured architectural and project plans with trade-off analysis",
            "general": "Handles general-purpose tasks with systematic analysis and quality focus"
        }

        return descriptions.get(
            task_type,
            f"Performs {task_type.replace('_', ' ')} tasks with quality and best practices"
        )

    def _create_workflow_template(self, task_type: str, specification: str) -> str:
        """Create static workflow section based on task type (template fallback)."""

        workflows = {
            "test_generation": """
1. **Analyze Code**: Read and understand the code to be tested
2. **Identify Test Cases**: Determine test scenarios including:
   - Happy path cases
   - Edge cases
   - Error conditions
3. **Write Tests**: Create test functions with clear assertions
4. **Verify Coverage**: Ensure comprehensive test coverage
5. **Run Tests**: Execute tests and verify they pass
""",
            "security_audit": """
1. **Reconnaissance**: Scan code for common vulnerability patterns
2. **Analysis**: Identify potential security issues:
   - Input validation gaps
   - Authentication/authorization flaws
   - Data exposure risks
3. **Risk Assessment**: Categorize findings by severity
4. **Remediation**: Provide specific fixes for each issue
5. **Verification**: Confirm fixes address vulnerabilities
""",
            "documentation": """
1. **Understand Code**: Read and analyze code structure
2. **Identify Key Concepts**: Determine what needs documentation
3. **Write Documentation**: Create clear docs with:
   - Purpose and overview
   - API/interface details
   - Usage examples
   - Edge cases and limitations
4. **Review**: Ensure documentation is accurate and complete
""",
            "performance_optimization": """
1. **Profile**: Identify performance bottlenecks
2. **Analyze**: Determine root causes (algorithms, I/O, etc.)
3. **Optimize**: Apply targeted improvements:
   - Algorithm optimization
   - Caching strategies
   - Resource management
4. **Benchmark**: Measure performance improvements
5. **Validate**: Ensure functionality preserved
""",
            "debugging": """
1. **Reproduce**: Understand and reproduce the issue
2. **Isolate**: Narrow down the location of the bug
3. **Analyze**: Identify root cause through:
   - Log analysis
   - Code tracing
   - State inspection
4. **Fix**: Implement targeted fix
5. **Test**: Verify fix resolves issue without side effects
""",
            "research": """
1. **Clarify Scope**: Identify the specific topic, timeframe, and depth required
2. **Gather Sources**: Search for authoritative references, papers, and documentation
3. **Evaluate Credibility**: Assess source reliability, recency, and relevance
4. **Synthesize Findings**: Organize information into coherent themes
5. **Summarize**: Produce a structured summary with citations and key takeaways
""",
            "writing": """
1. **Understand Audience**: Identify the target readers and their knowledge level
2. **Outline Structure**: Plan sections, flow, and key points to cover
3. **Draft Content**: Write clear, well-organized prose with appropriate tone
4. **Review**: Check for clarity, accuracy, completeness, and logical flow
5. **Polish**: Refine language, fix grammar, and ensure consistent style
""",
            "data_analysis": """
1. **Understand the Data**: Identify data sources, schema, and quality issues
2. **Clean and Prepare**: Handle missing values, outliers, and format inconsistencies
3. **Explore Patterns**: Run descriptive statistics and identify distributions
4. **Analyze**: Apply appropriate methods (statistical, visual, or computational)
5. **Communicate Results**: Present findings with clear visualizations and narrative
""",
            "planning": """
1. **Analyze Requirements**: Break down the problem into constraints and goals
2. **Survey Options**: Identify viable approaches, technologies, and trade-offs
3. **Design Architecture**: Propose a structured solution with clear component boundaries
4. **Assess Risks**: Identify failure modes, scalability concerns, and unknowns
5. **Deliver Plan**: Produce a step-by-step implementation roadmap with milestones
""",
        }

        return workflows.get(task_type, """
1. **Analyze**: Understand the requirements and context
2. **Plan**: Design approach to meet requirements
3. **Execute**: Implement the solution
4. **Validate**: Verify output meets quality standards
5. **Refine**: Improve based on validation results
""")

    @staticmethod
    def _create_best_practices_template(task_type: str) -> str:
        """Create static best practices section (template fallback)."""
        return f"""
## Best Practices

1. **Understand Requirements**: Carefully read the specification
2. **Follow Patterns**: Use established patterns for {task_type}
3. **Validate Quality**: Check output meets requirements
4. **Document Decisions**: Explain key implementation choices
"""

    @staticmethod
    def _allowed_tools_for_task(task_type: str) -> str:
        """Return the allowed-tools declaration appropriate for a task type."""
        # Code-centric tasks need write/execute access
        code_tasks = {
            "code_generation", "test_generation", "debugging",
            "refactoring", "performance_optimization",
        }
        if task_type in code_tasks:
            return "Bash Read Write Edit"

        # Security audits read code but may run scanners
        if task_type == "security_audit":
            return "Bash Read Grep Glob"

        # Read-only / text-output tasks
        return "Read Grep Glob WebFetch WebSearch"

    @staticmethod
    def _quality_criteria_for_task(task_type: str) -> list:
        """Return skill-level quality criteria for the critic, or empty list."""
        criteria_map = {
            "research": [
                "Source Credibility: Are claims backed by authoritative references?",
                "Depth: Does the research go beyond surface-level summaries?",
                "Recency: Is the information current and not outdated?",
                "Balance: Are multiple perspectives or trade-offs presented?",
                "Actionability: Can the reader act on the findings?",
            ],
            "writing": [
                "Clarity: Is the prose clear and free of jargon for the target audience?",
                "Structure: Is the content logically organized with smooth transitions?",
                "Completeness: Are all requested topics covered?",
                "Tone: Is the writing style appropriate for the context?",
                "Grammar: Is the text free of spelling and grammatical errors?",
            ],
            "data_analysis": [
                "Methodology: Is the analytical approach appropriate for the data?",
                "Accuracy: Are calculations and statistics correct?",
                "Visualization: Are charts and tables clear and well-labeled?",
                "Insight: Does the analysis surface non-obvious findings?",
                "Reproducibility: Could someone replicate the analysis from the description?",
            ],
            "planning": [
                "Feasibility: Is the proposed plan realistic given constraints?",
                "Completeness: Are all major components and dependencies addressed?",
                "Trade-offs: Are alternatives discussed with pros and cons?",
                "Risk Assessment: Are failure modes and mitigations identified?",
                "Actionability: Does the plan include concrete next steps?",
            ],
            "documentation": [
                "Accuracy: Does the documentation match the actual code behavior?",
                "Completeness: Are all public APIs and parameters documented?",
                "Examples: Are usage examples provided for non-trivial functions?",
                "Clarity: Can a new developer understand the code from the docs alone?",
                "Format: Does it follow the project's docstring convention?",
            ],
        }
        return criteria_map.get(task_type, [])


def generate_skills(
    state: AgentState,
    skill_registry: SkillRegistry,
    outcome_store: Optional[SkillOutcomeStore] = None,
    base_model: Any = None,
    adapter_registry: Any = None,
) -> AgentState:
    """
    Convenience function for graph integration.

    Args:
        state: Current agent state
        skill_registry: Shared SkillRegistry instance
        outcome_store:  Optional SkillOutcomeStore for RAG
        base_model:     Optional LLM backend for tailored generation
        adapter_registry: Optional AdapterRegistry for simulation-based vetting

    Returns:
        Updated state with generated skills
    """
    generator = SkillGeneratorNode(
        skill_registry, outcome_store=outcome_store, base_model=base_model,
        adapter_registry=adapter_registry,
    )
    return generator.execute(state)
